### ISSUE TITLE
OAuthError: [200] (#200) App cannot edit non-app posts

### ISSUE THREAD

**Issue by Waffleboy** [jgorset/facepy#149]
Hello,

I'm trying to make a (hopefully) useful script, which bascially sets all the privacy of posts beyond a certain date to 'only me'. I'm using the token from graphAPI for permissions.

I'm able to get posts,but when I try to update the privacy setting of the post, i get:

OAuthError: [200] (#200) App cannot edit non-app posts

Nearly every permission is enabled in the graphAPI page (https://developers.facebook.com/tools/explorer/) Is there a way to achieve my objective with this token? or is the only way to create an actual app, request the permission from facebook then do it? =/ That seems overly obstructive for a simple use case..

**Comment by jgorset** [comment]
That's pretty useful! I haven't tried doing anything like that before, but judging from the error message Facebook just won't let you edit posts that aren't made by the application you got the token from. Making your own application won't help, then, because those posts aren't made by _any_ application.

![Very sad](http://24.media.tumblr.com/tumblr_maepfnpu6l1qc2i56o1_500.jpg)
